config/routes.rb
Rails.application.routes.draw do
  get 'footer/agb'
  get 'footer/impressum'
  get 'footer/wiederrufsrecht'
  get 'footer/datenschutz'
  get 'appnumbers/one'
  get 'appnumbers/two'
  get 'appnumbers/tree'
  get 'appnumbers/four'
  get 'appnumbers/five'
  get 'appnumbers/six'
  get 'appnumbers/seven'
  get 'appnumbers/eight'
  get 'flats/index'
  get 'contacts/new'
  get 'contact/create'
  get 'contacts/thanks'
  get 'infos/new'
  get 'infos/index'
  get 'infos/show'
  get 'infos/update'
  get 'informations/about'
  get 'informations/price'
  get 'informations/location'
  get 'informations/contact'
  get 'informations/contact'

  # get 'information/contact'
  # get 'information/price'
  # get 'information/about'
  # get 'information/location'
  # get 'information/appartments'
  get 'appartments/index'
  get 'appartments/show'
  get 'appartments/new'
  get 'appartments/create'
  get 'appartments/update'
  get 'appartments/edit'
  get 'appartments/destroy'
  # post "contacts", to: "contacts#create"
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :contacts, only: [ :new, :create ]
  # get '/contact', to: 'pages#contact'
  # resources :contacts, only: [ :new, :create ]
  # get 'about', to: 'pages#about'
  # root to: 'contacts#contact'
  # get '/contact', to: 'contacts#contact'
  # resources :contacts, only: [ :new, :create ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

# get "contacts#new", :as => :new_contact
# post "contacts#create", :as => :new_contact

app/models/about.rb
class About < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,
    :presence => :true,
    :format => {
      :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      :message => "must be a valid email address"
    }
  validates :message, :presence => :true
  # validates :firstname, :presence => :true
  # validates :lastname, :presence => :true
  validates :name, :presence => :true

  validates :telephonenumber, :presence => :true

  def headers
    {
      :subject => "My Contact Form",
      :to => "s.nesselhauf@hv-n.de",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?
end

app/models/photo_uploader.rb
class PhotoUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
         # :recoverable, :rememberable, :validatable
end

app/controllers/appartments_controller.rb
class AppartmentsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/appnumbers_controller.rb
class AppnumbersController < ApplicationController
  def one
  end

  def two
  end

  def tree
  end

  def four
  end

  def five
  end

  def six
  end

  def seven
  end

  def eight
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
       ContactsMailer.general_message(@contact).deliver_now
       redirect_to new_contact_path, notice: "Message sent."
       # render :thanks
    else
       redirect_to new_contact_path, notice: "Error occured."

    end
  end

  def thanks
  end

  def wiederrufsrecht
  end

  def datenschutz
  end

  private

  def contact_params
      params.require(:contact).permit(:name, :email, :message, :telephonenumber)
    end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
# @flats = Flat.where.not(latitude: nil, longitude: nil)

#     @markers = @flats.map do |flat|
#       {
#         lat: flat.latitude,
#         lng: flat.longitude#,

    # @flats = Flat.geocoded # returns flats with coordinates

    # @markers = @flats.map do |flat|
    #   {
    #     lat: flat.latitude,
    #     lng: flat.longitude
      # }
    end
  end
end

app/controllers/footer_controller.rb
class FooterController < ApplicationController
  def agb
  end

  def impressum
  end

  def wiederrufsrecht
  end

  def datenschutz
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  def about
  end

  def price
  end

  def location
  end

  def contact
  end

  def agb
  end

  def impressum
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def home
    # @flats = Flat.geocoded #returns flats with coordinates

    # @markers = @flats.map do |flat|
    #   {
    #     lat: flat.latitude,
    #     lng: flat.longitude
    #   }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def homepage?
    current_page?('/')
  end
end

app/views/appartments/create.html.erb
<h1>Appartments#create</h1>
<p>Find me in app/views/appartments/create.html.erb</p>

app/views/appartments/destroy.html.erb
<h1>Appartments#destroy</h1>
<p>Find me in app/views/appartments/destroy.html.erb</p>

app/views/appartments/edit.html.erb
<h1>Appartments#edit</h1>
<p>Find me in app/views/appartments/edit.html.erb</p>

app/views/appartments/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<div class="cards-container">
  <h1 style="margin-top: 100px; text-align: center;">Unsere Appartments im Überblick</h1>
  <div class="row row-cols-1 row-cols-md-2">
<!------------------appartment 1------------------->
  <div class="col mb-4">
    <div class="card" style="margin: 20px 20px 20px 100px;">
     <div class="card-img-top w3-hover-opacity" id="img01" style="background-image: url('<%= image_path "app-3.jpeg"%>'); width: auto;height: 300px; object-fit: cover; cursor:pointer" onclick="onClick(this)" class="w3-hover-opacity">
      </div>
      <div class="card-body">
        <h5 class="card-title">Appartment 1</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <button class="home-app-btn" style="margin: 6px;"><%= link_to "Kontakt", contacts_new_path, style: "font-size: 15px" %></button>
        <button class="home-app-btn" style="margin: 6px;"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank" style="font-size: 15px">Jetzt Buchen</a></button>
      </div>
    </div>
  </div>
  <!------------------appartment 2------------------->
  <div class="col mb-4">
    <div class="card" style="margin: 20px 100px 20px 20px;">
     <div class="card-img-top w3-hover-opacity" id="img02" style="background-image: url('<%= image_path "app-8.jpeg"%>'); width: auto;height: 300px; object-fit: cover; cursor:pointer" onclick="onClick(this)" class="w3-hover-opacity">
      </div>
      <div class="card-body">
        <h5 class="card-title">Appartment 2</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <button class="home-app-btn" style="margin: 6px;"><%= link_to "Kontakt", contacts_new_path, style: "font-size: 15px" %></button>
        <button class="home-app-btn" style="margin: 6px;"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank" style="font-size: 15px">Jetzt Buchen</a></button>
      </div>
    </div>
  </div>
  <!------------------appartment 3------------------->
  <div class="col mb-4">
    <div class="card" style="margin: 20px 20px 20px 100px;">
     <div class="card-img-top" style="background-image: url('<%= image_path "app-3.jpeg" %>'); width: auto;height: 300px; object-fit: cover">
      </div>
      <div class="card-body">
        <h5 class="card-title">Appartment 3</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <button class="home-app-btn" style="margin: 6px;"><%= link_to "Kontakt", contacts_new_path, style: "font-size: 15px" %></button>
        <button class="home-app-btn" style="margin: 6px;"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank" style="font-size: 15px">Jetzt Buchen</a></button>
      </div>
    </div>
  </div>
  <!------------------appartment 4------------------->
  <div class="col mb-4">
    <div class="card" style="margin: 20px 100px 20px 20px;">
     <div class="card-img-top" style="background-image: url('<%= image_path "app-3.jpeg" %>'); width: auto;height: 300px; object-fit: cover">
      </div>
      <div class="card-body">
        <h5 class="card-title">Appartment 4</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <button class="home-app-btn" style="margin: 6px;"><%= link_to "Kontakt", contacts_new_path, style: "font-size: 15px" %></button>
        <button class="home-app-btn" style="margin: 6px;"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank" style="font-size: 15px">Jetzt Buchen</a></button>
      </div>
    </div>
  </div>
  <!------------------appartment 5------------------->
  <div class="col mb-4">
    <div class="card" style="margin: 20px 20px 20px 100px;">
     <div class="card-img-top" style="background-image: url('<%= image_path "app-3.jpeg" %>'); width: auto;height: 300px; object-fit: cover">
      </div>
      <div class="card-body">
        <h5 class="card-title">Appartment 5</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <button class="home-app-btn" style="margin: 6px;"><%= link_to "Kontakt", contacts_new_path, style: "font-size: 15px" %></button>
        <button class="home-app-btn" style="margin: 6px;"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank" style="font-size: 15px">Jetzt Buchen</a></button>
      </div>
    </div>
  </div>
  <!------------------appartment 6------------------->
  <div class="col mb-4">
    <div class="card" style="margin: 20px 100px 20px 20px;">
     <div class="card-img-top" style="background-image: url('<%= image_path "app-3.jpeg" %>'); width: auto;height: 300px; object-fit: cover">
      </div>
      <div class="card-body">
        <h5 class="card-title">Appartment 6</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <button class="home-app-btn" style="margin: 6px;"><%= link_to "Kontakt", contacts_new_path, style: "font-size: 15px" %></button>
        <button class="home-app-btn" style="margin: 6px;"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank" style="font-size: 15px">Jetzt Buchen</a></button>
      </div>
    </div>
  </div>
  <!------------------appartment 7------------------->
  <div class="col mb-4">
    <div class="card" style="margin: 20px 20px 20px 100px;">
     <div class="card-img-top" style="background-image: url('<%= image_path "app-3.jpeg" %>'); width: auto;height: 300px; object-fit: cover">
      </div>
      <div class="card-body">
        <h5 class="card-title">Appartment 7</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <button class="home-app-btn" style="margin: 6px;"><%= link_to "Kontakt", contacts_new_path, style: "font-size: 15px" %></button>
        <button class="home-app-btn" style="margin: 6px;"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank" style="font-size: 15px">Jetzt Buchen</a></button>
      </div>
    </div>
  </div>
  <!------------------appartment 8------------------->
  <div class="col mb-4">
    <div class="card" style="margin: 20px 100px 20px 20px;">
     <div class="card-img-top" style="background-image: url('<%= image_path "app-3.jpeg" %>'); width: auto;height: 300px; object-fit: cover">
      </div>
      <div class="card-body">
        <h5 class="card-title">Appartment 8</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <button class="home-app-btn" style="margin: 6px;"><%= link_to "Kontakt", contacts_new_path, style: "font-size: 15px" %></button>
        <button class="home-app-btn" style="margin: 6px;"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank" style="font-size: 15px">Jetzt Buchen</a></button>
      </div>
    </div>
  </div>
</div>
</div>

<!------------------ab hier Modul für appartment 1------------------->

<div id="modal01" class="w3-modal" onclick="this.style.display='none'">
  <span class="w3-button w3-hover-red w3-xlarge w3-display-topright">&times;</span>
  <div class="w3-modal-content w3-animate-zoom">
    <h5 id="img01">Appartment 7</h5>
  </div>
</div>
<script>
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
}
</script>

<!--
<script>
document.getElementsByClassName("tablink")[0].click();

function openCity(evt, cityName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
    tablinks[i].classList.remove("w3-light-grey");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.classList.add("w3-light-grey");
}
</script>
-->

<!------------------ab hier Modul für appartment 2------------------->

<!--<div id="modal02" class="w3-modal">
 <div class="w3-modal-content w3-card-4 w3-animate-zoom">
  <header class="w3-container w3-blue">
   <span onclick="document.getElementById('modal02').style.display='none'"
   class="w3-button w3-blue w3-xlarge w3-display-topright">&times;</span>
   <h2 id="modal02">Appartment 2</h2>
  </header>

  <div class="w3-bar w3-border-bottom">
   <button class="tablink w3-bar-item w3-button" onclick="openCity(event, 'London')">London</button>
   <button class="tablink w3-bar-item w3-button" onclick="openCity(event, 'Paris')">Paris</button>
   <button class="tablink w3-bar-item w3-button" onclick="openCity(event, 'Tokyo')">Tokyo</button>
  </div>

  <div id="London" class="w3-container city">
   <h1>London</h1>
   <p>London is the most populous city in the United Kingdom, with a metropolitan area of over 9 million inhabitants.</p>
   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>

  <div id="Paris" class="w3-container city">
   <h1>Paris</h1>
   <p>Paris is the capital of France.</p>
   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
  </div>

  <div id="Tokyo" class="w3-container city">
   <h1>Tokyo</h1>
   <p>Tokyo is the capital of Japan.</p><br>
  </div>

  <div class="w3-container w3-light-grey w3-padding">
   <button class="w3-button w3-right w3-white w3-border"
   onclick="document.getElementById('modal02').style.display='none'">Close</button>
  </div>
 </div>
</div>
<script>
function onClick(element) {
  document.getElementById("img02").src = element.src;
  document.getElementById("modal02").style.display = "block";
}
</script>

app/views/appartments/new.html.erb
<h1>Appartments#new</h1>
<p>Find me in app/views/appartments/new.html.erb</p>

app/views/appartments/show.html.erb
<h1>Appartments#show</h1>
<p>Find me in app/views/appartments/show.html.erb</p>

app/views/appartments/update.html.erb
<h1>Appartments#update</h1>
<p>Find me in app/views/appartments/update.html.erb</p>

app/views/appnumbers/eight.html.erb
<h1>Appnumbers#eight</h1>
<p>Find me in app/views/appnumbers/eight.html.erb</p>

app/views/appnumbers/five.html.erb
<h1>Appnumbers#five</h1>
<p>Find me in app/views/appnumbers/five.html.erb</p>

app/views/appnumbers/four.html.erb
<h1>Appnumbers#four</h1>
<p>Find me in app/views/appnumbers/four.html.erb</p>

app/views/appnumbers/one.html.erb
<h1>Appnumbers#one</h1>
<p>Find me in app/views/appnumbers/one.html.erb</p>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("app-3.jpeg", :alt => "see what we do",  :class => "d-block w-100") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("app-4.jpeg", :alt => "see what we do",  :class => "d-block w-100") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("app-8.jpeg", :alt => "see what we do",  :class => "d-block w-100") %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/appnumbers/seven.html.erb
<h1>Appnumbers#seven</h1>
<p>Find me in app/views/appnumbers/seven.html.erb</p>

app/views/appnumbers/six.html.erb
<h1>Appnumbers#six</h1>
<p>Find me in app/views/appnumbers/six.html.erb</p>

app/views/appnumbers/tree.html.erb
<h1>Appnumbers#tree</h1>
<p>Find me in app/views/appnumbers/tree.html.erb</p>

app/views/appnumbers/two.html.erb
<h1>Appnumbers#two</h1>
<p>Find me in app/views/appnumbers/two.html.erb</p>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<div style="padding: 50px;">
  <div class="contact-header">
    <h2 style="margin: 30px;"><strong>Kontakt</strong></h1>
      <p style="text-align: left;">Was ist dein Anliegen? Gibt es ein Problem mit deiner Buchung? Hast du eine Frage zu unseren Appartments? Oder möchtest du uns einfach mal ein Kompliment machen? So oder so haben wir jederzeit ein offenes Ohr für dich! Füll einfach das Formular aus und wir melden uns innerhalb von 24h bei dir zurück.</p>
  </div>

  <%= render 'form' %>
</div>

app/views/contacts/thanks.html.erb
<h1>Contacts#thanks</h1>
<p>Find me in app/views/contacts/thanks.html.erb</p>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('<%= image_path "banner-6.jpg" %>');">
  <div class="container">
    <h3 style="font-size: 120px; margin-bottom: 0px">ART´hüs</h3>
    <p> <strong>- Wilkommen in Westerland auf Sylt -</strong></p>
        <button class="home-app-btn"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank">Verfügbarkeit prüfen</a></button>
  </div>
</div>

<div class="block-1">
      <p style="color: #A39EA9;"><strong>______________</strong></p>
      <h1>
        <strong>Zentrale Lage zu Strand und Stadt</strong>
      </h1>
      <p style="text-align: center; margin: 0 200px 20px 200px; font-size: 20px; opacity: 70%">Das ART'hüs ist in zentraler Lage Westerlands, ca. 500 m zum Strand am Ende
          der Straße und auch nur ca. 300 m vom Zentrum entfernt.
          Bushaltestelle ist vor der Tür.</p>
      <button class="home-app-btn"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank">Verfügbarkeit prüfen</a></button>
  </div>

  <div class="block-2">
    <div class="in-block-left" >
      <%= image_tag("strand-2.jpg", :alt => "this is our team", :class => "team-img") %>
    </div>
    <div class="in-block-right" style="background-color: #F6E9E8">
      <h1 style="position: center; color: #6E5F5E; font-size: 40px;">Über uns</h1>
    </div>
    <div class="overlay">
      <div class="text-about-us">
        <h3 class="text-break">Das ART'hüs wurde im Sommer 2002 eröffnet. Wir sind ein modernes und farbenfrohes Haus, welches eine Verbindung von Ferienwohnungen mit wechselnden Kunstausstellungen bietet. In allen Wohnungen hängen ausschließlich Unikate von Vertretern der "Modern Art".</h3>
      </div>
    </div>
  </div>

  <div class="block-1">
      <p style="color: #A39EA9"><strong>______________</strong></p>
      <h1 style="font-size: 25px; opacity: 70%">Im ART'hüs präsentieren wir Ihnen ständig wechselnde <strong>Kunstausstellungen</strong> und in allen Wohnungen hängen ausschließlich Unikate.
      </h1>
      <p style="color: #A39EA9"><strong>______________</strong></p>
  </div>

  <div class="block-3">
    <div class="in-block-right" style="background-color: #A39EA9;">
      <h1 style="position: center;">Unsere Appartments</h1>
    </div>
    <div class="in-block-left">
      <title>W3.CSS</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
      <style>
      .mySlides {display:none}
      .w3-left, .w3-right, .w3-badge {cursor:pointer}
      .w3-badge {height:13px;width:13px;padding:0}
      </style>
      <div class="w3-content w3-display-container" style="max-width:800px">
        <%= image_tag("app-3.jpeg", :alt => "see what we do",  :class => "mySlides") %>
        <%= image_tag("app-4.jpg", :alt => "see what we do", :class => "mySlides") %>
        <%= image_tag("app-8.jpg", :alt => "see what we do",  :class => "mySlides") %>
        <div class="w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle" style="width:100%">
          <div class="w3-left w3-hover-text-khaki" onclick="plusDivs(-1)">&#10094;</div>
          <div class="w3-right w3-hover-text-khaki" onclick="plusDivs(1)">&#10095;</div>
          <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(1)"></span>
          <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(2)"></span>
          <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(3)"></span>
        </div>
      </div>
      <!-- <script src="appSlideshow.js"></script> -->
    </div>
    <div class="overlay-home-app">
      <div class="text-about-us">
        <h3 class="text-break">In unseren 8 Appartments mit Platz für 1-4 Personen können Sie sich wie Zuhause fühlen.</h3>
        <button class="home-app-btn" ><%= link_to "Zu den Appartments", appartments_index_path %></button>
      </div>
    </div>
  </div>

  <div class="block-1">
      <p style="color: #A39EA9"><strong>______________</strong></p>
      <h1 style="font-size: 25px; opacity: 70%">Das ART'hüs ist besonders
        <strong>kinderfreundlich</strong> und freut sich über alle kleinen Gäste. Ob bei Sonne auf dem Trampolin im Garten oder bei Regen im Spielzimmer. Bei uns hat man immer Spaß.
      </h1>
      <p style="color: #A39EA9"><strong>______________</strong></p>
  </div>

  <div class="block-2">
    <div class="in-block-left">
      <%= image_tag("banner-5.jpg", :alt => "this is our team", :class => "team-img") %>
    </div>
    <div class="in-block-right" style="background-color: #F6E9E8">
      <h1 style="position: center;color: #6E5F5E; font-size: 40px;">KONTAKT</h1>
    </div>
    <div class="overlay-contact">
      <div class="text-contact">
        <div class="contact-flex">
          <p>Möchten Sie weitere Informationen anfordern oder uns eine Buchungsanfrage zukommen lassen? Rufen Sie uns einfach an oder schreiben Sie eine <%= link_to "E-mail", contacts_new_path, class: "nav-link"%>.</p>
              </%>
        </div>
      </div>
    </div>
  </div>

  <div class="block-1">
      <p style="color: #A39EA9"><strong>______________</strong></p>
      <h1 style="font-size: 25px; opacity: 70%">Wir freuen uns Sie schon bald bei uns <strong>Wilkommen</strong> zu heißen.
      </h1>
      <p style="color: #A39EA9"><strong>______________</strong></p>
  </div>

app/views/shared/_navbar.html.erb
    <div class="navbar navbar-expand-sm ">

      <div class="navbar-left">
        <div class="logo-btn-sm">
          <%= link_to "ART´hüs", root_path, class: "nav-link" %>
        </div>
      </div>



      <div class="navbar-right">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>



        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "Über uns", informations_about_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Kontakt", contacts_new_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Preise", informations_price_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Lage", flats_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Appartments", appartments_index_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <button class="home-app-btn" style="margin: 6px;"><a href="http://visitenkarten.im-web.de/55004/belegung.php" target="_blank" style="font-size: 15px">Jetzt Buchen</a></button>
            </li>
        </ul>
      </div>
</div>